#!/bin/bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

DEFAULT_COMPILER=$(echo "$(make -p -f /dev/null 2>&1 | grep -vi '\$\|\*' | grep -i "cxx")" | cut -f2 -d"="  | tr -d ' ')

CLANG_CHECK=$DEFAULT_COMPILER 2>&1 | grep "clang"

GOAL=$1

if [[ -z "$GOAL" ]]; then
	echo "usage: agile-config {compile, link, build} [--root]"
	exit
fi
if [[ "$GOAL" == "compile" ]]; then
	if [[ $2 == "--root" ]]; then
		ROOTSTUFF="`root-config --cflags`"
	fi
	COMMAND="-std=c++11 -Wall -fPIC -I$DIR $ROOTSTUFF"
fi
if [[ "$GOAL" == "link" ]]; then
	if [[ $2 == "--root" ]]; then
		ROOTSTUFF="`root-config --ldflags` `root-config --libs`"
	fi
	COMMAND="-L$DIR/lib -lAGILEPack $ROOTSTUFF"

fi

if [[ "$GOAL" == "build" ]]; then
	if [[ $2 == "--root" ]]; then
		ROOTSTUFF="`root-config --ldflags` `root-config --libs`"
		ROOTCFLAGS="`root-config --cflags`"
	fi
	COMMAND="-std=c++11 -Wall -fPIC -I$DIR $ROOTCFLAGS -L$DIR/lib -lAGILEPack $ROOTSTUFF"
fi

if [[ "$GOAL" == "build" ]] || [["$GOAL" == "link"]]; then
	if [[ -n "$CLANG_CHECK" ]] && [[ -z "$(echo $COMMAND | grep "-stdlib=libc++")" ]]; then
		echo "not found!"
		COMMAND="$COMMAND -stdlib=libc++"
	fi
fi


echo $COMMAND
